// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: person.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Simon.GrpcService.API {

  /// <summary>Holder for reflection information generated from person.proto</summary>
  public static partial class PersonReflection {

    #region Descriptor
    /// <summary>File descriptor for person.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PersonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxwZXJzb24ucHJvdG8SGkFjYWRzb2MuR3JwY1NlcnZpY2UuU2VydmVyGhtn",
            "b29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi9U",
            "aW1lc3RhbXAucHJvdG8iGwoNUmVxdWVzdFVzZXJJZBIKCgJJZBgBIAEoBSJG",
            "ChBSZXNwb25zZVVzZXJJbmZvEjIKBnBlcnNvbhgBIAEoCzIiLkFjYWRzb2Mu",
            "R3JwY1NlcnZpY2UuU2VydmVyLlBlcnNvbiJHChFSZXBvbnNlUGVyc29uTGlz",
            "dBIyCgZwZXJzb24YASADKAsyIi5BY2Fkc29jLkdycGNTZXJ2aWNlLlNlcnZl",
            "ci5QZXJzb24i6AEKBlBlcnNvbhIKCgJJZBgBIAEoBRIMCgRuYW1lGAIgASgJ",
            "EgsKA2FnZRgDIAEoBRIyCgZnZW5kZXIYBCABKA4yIi5BY2Fkc29jLkdycGNT",
            "ZXJ2aWNlLlNlcnZlci5HZW5kZXISDgoGd2VpZ2h0GAUgASgCEhYKDmVtYWls",
            "X3ZlcmlmaWVkGAYgASgIEg0KBXBob25lGAcgAygJEg4KBnNhbGFyeRgIIAEo",
            "ARIyCgVteUFkZBgJIAMoCzIjLkFjYWRzb2MuR3JwY1NlcnZpY2UuU2VydmVy",
            "LkFkZHJlc3NSA2Zvb1IDYmFyImkKB0FkZHJlc3MSEAoIcHJvdmluY2UYASAB",
            "KAkSDAoEY2l0eRgCIAEoCRIMCgRhcmVhGAMgASgJEhAKCHppcF9jb2RlGAQg",
            "ASgJEg4KBnN0cmVldBgFIAEoCRIOCgZudW1iZXIYBiABKAkqQgoGR2VuZGVy",
            "EgoKBlVOS05PVxAAEgoKBkZFTUFMRRABEggKBE1BTEUQAhIJCgVXT01BThAB",
            "EgcKA01BThACGgIQATLOAQoNUGVyc29uU2VydmljZRJsChFHZXRQZXJzb25J",
            "bmZvQnlJZBIpLkFjYWRzb2MuR3JwY1NlcnZpY2UuU2VydmVyLlJlcXVlc3RV",
            "c2VySWQaLC5BY2Fkc29jLkdycGNTZXJ2aWNlLlNlcnZlci5SZXNwb25zZVVz",
            "ZXJJbmZvEk8KBkdldEFsbBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRotLkFj",
            "YWRzb2MuR3JwY1NlcnZpY2UuU2VydmVyLlJlcG9uc2VQZXJzb25MaXN0Qhiq",
            "AhVTaW1vbi5HcnBjU2VydmljZS5BUEliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Simon.GrpcService.API.Gender), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Simon.GrpcService.API.RequestUserId), global::Simon.GrpcService.API.RequestUserId.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Simon.GrpcService.API.ResponseUserInfo), global::Simon.GrpcService.API.ResponseUserInfo.Parser, new[]{ "Person" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Simon.GrpcService.API.ReponsePersonList), global::Simon.GrpcService.API.ReponsePersonList.Parser, new[]{ "Person" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Simon.GrpcService.API.Person), global::Simon.GrpcService.API.Person.Parser, new[]{ "Id", "Name", "Age", "Gender", "Weight", "EmailVerified", "Phone", "Salary", "MyAdd" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Simon.GrpcService.API.Address), global::Simon.GrpcService.API.Address.Parser, new[]{ "Province", "City", "Area", "ZipCode", "Street", "Number" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Gender {
    [pbr::OriginalName("UNKNOW")] Unknow = 0,
    [pbr::OriginalName("FEMALE")] Female = 1,
    [pbr::OriginalName("MALE")] Male = 2,
    [pbr::OriginalName("WOMAN", PreferredAlias = false)] Woman = 1,
    [pbr::OriginalName("MAN", PreferredAlias = false)] Man = 2,
  }

  #endregion

  #region Messages
  public sealed partial class RequestUserId : pb::IMessage<RequestUserId> {
    private static readonly pb::MessageParser<RequestUserId> _parser = new pb::MessageParser<RequestUserId>(() => new RequestUserId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestUserId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Simon.GrpcService.API.PersonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestUserId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestUserId(RequestUserId other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestUserId Clone() {
      return new RequestUserId(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestUserId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestUserId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestUserId other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResponseUserInfo : pb::IMessage<ResponseUserInfo> {
    private static readonly pb::MessageParser<ResponseUserInfo> _parser = new pb::MessageParser<ResponseUserInfo>(() => new ResponseUserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseUserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Simon.GrpcService.API.PersonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseUserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseUserInfo(ResponseUserInfo other) : this() {
      person_ = other.person_ != null ? other.person_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseUserInfo Clone() {
      return new ResponseUserInfo(this);
    }

    /// <summary>Field number for the "person" field.</summary>
    public const int PersonFieldNumber = 1;
    private global::Simon.GrpcService.API.Person person_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Simon.GrpcService.API.Person Person {
      get { return person_; }
      set {
        person_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseUserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseUserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Person, other.Person)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (person_ != null) hash ^= Person.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (person_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Person);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (person_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Person);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseUserInfo other) {
      if (other == null) {
        return;
      }
      if (other.person_ != null) {
        if (person_ == null) {
          Person = new global::Simon.GrpcService.API.Person();
        }
        Person.MergeFrom(other.Person);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (person_ == null) {
              Person = new global::Simon.GrpcService.API.Person();
            }
            input.ReadMessage(Person);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReponsePersonList : pb::IMessage<ReponsePersonList> {
    private static readonly pb::MessageParser<ReponsePersonList> _parser = new pb::MessageParser<ReponsePersonList>(() => new ReponsePersonList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReponsePersonList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Simon.GrpcService.API.PersonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReponsePersonList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReponsePersonList(ReponsePersonList other) : this() {
      person_ = other.person_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReponsePersonList Clone() {
      return new ReponsePersonList(this);
    }

    /// <summary>Field number for the "person" field.</summary>
    public const int PersonFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Simon.GrpcService.API.Person> _repeated_person_codec
        = pb::FieldCodec.ForMessage(10, global::Simon.GrpcService.API.Person.Parser);
    private readonly pbc::RepeatedField<global::Simon.GrpcService.API.Person> person_ = new pbc::RepeatedField<global::Simon.GrpcService.API.Person>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Simon.GrpcService.API.Person> Person {
      get { return person_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReponsePersonList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReponsePersonList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!person_.Equals(other.person_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= person_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      person_.WriteTo(output, _repeated_person_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += person_.CalculateSize(_repeated_person_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReponsePersonList other) {
      if (other == null) {
        return;
      }
      person_.Add(other.person_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            person_.AddEntriesFrom(input, _repeated_person_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Person : pb::IMessage<Person> {
    private static readonly pb::MessageParser<Person> _parser = new pb::MessageParser<Person>(() => new Person());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Person> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Simon.GrpcService.API.PersonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Person() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Person(Person other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      age_ = other.age_;
      gender_ = other.gender_;
      weight_ = other.weight_;
      emailVerified_ = other.emailVerified_;
      phone_ = other.phone_.Clone();
      salary_ = other.salary_;
      myAdd_ = other.myAdd_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Person Clone() {
      return new Person(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 4;
    private global::Simon.GrpcService.API.Gender gender_ = global::Simon.GrpcService.API.Gender.Unknow;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Simon.GrpcService.API.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 5;
    private float weight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "email_verified" field.</summary>
    public const int EmailVerifiedFieldNumber = 6;
    private bool emailVerified_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EmailVerified {
      get { return emailVerified_; }
      set {
        emailVerified_ = value;
      }
    }

    /// <summary>Field number for the "phone" field.</summary>
    public const int PhoneFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_phone_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> phone_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///允许重复利用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Phone {
      get { return phone_; }
    }

    /// <summary>Field number for the "salary" field.</summary>
    public const int SalaryFieldNumber = 8;
    private double salary_;
    /// <summary>
    ///Date birthday = 9;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Salary {
      get { return salary_; }
      set {
        salary_ = value;
      }
    }

    /// <summary>Field number for the "myAdd" field.</summary>
    public const int MyAddFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Simon.GrpcService.API.Address> _repeated_myAdd_codec
        = pb::FieldCodec.ForMessage(74, global::Simon.GrpcService.API.Address.Parser);
    private readonly pbc::RepeatedField<global::Simon.GrpcService.API.Address> myAdd_ = new pbc::RepeatedField<global::Simon.GrpcService.API.Address>();
    /// <summary>
    ///多个地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Simon.GrpcService.API.Address> MyAdd {
      get { return myAdd_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Person);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Person other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Age != other.Age) return false;
      if (Gender != other.Gender) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Weight, other.Weight)) return false;
      if (EmailVerified != other.EmailVerified) return false;
      if(!phone_.Equals(other.phone_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Salary, other.Salary)) return false;
      if(!myAdd_.Equals(other.myAdd_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (Gender != global::Simon.GrpcService.API.Gender.Unknow) hash ^= Gender.GetHashCode();
      if (Weight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Weight);
      if (EmailVerified != false) hash ^= EmailVerified.GetHashCode();
      hash ^= phone_.GetHashCode();
      if (Salary != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Salary);
      hash ^= myAdd_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      if (Gender != global::Simon.GrpcService.API.Gender.Unknow) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Gender);
      }
      if (Weight != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Weight);
      }
      if (EmailVerified != false) {
        output.WriteRawTag(48);
        output.WriteBool(EmailVerified);
      }
      phone_.WriteTo(output, _repeated_phone_codec);
      if (Salary != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Salary);
      }
      myAdd_.WriteTo(output, _repeated_myAdd_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (Gender != global::Simon.GrpcService.API.Gender.Unknow) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (Weight != 0F) {
        size += 1 + 4;
      }
      if (EmailVerified != false) {
        size += 1 + 1;
      }
      size += phone_.CalculateSize(_repeated_phone_codec);
      if (Salary != 0D) {
        size += 1 + 8;
      }
      size += myAdd_.CalculateSize(_repeated_myAdd_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Person other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      if (other.Gender != global::Simon.GrpcService.API.Gender.Unknow) {
        Gender = other.Gender;
      }
      if (other.Weight != 0F) {
        Weight = other.Weight;
      }
      if (other.EmailVerified != false) {
        EmailVerified = other.EmailVerified;
      }
      phone_.Add(other.phone_);
      if (other.Salary != 0D) {
        Salary = other.Salary;
      }
      myAdd_.Add(other.myAdd_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 32: {
            Gender = (global::Simon.GrpcService.API.Gender) input.ReadEnum();
            break;
          }
          case 45: {
            Weight = input.ReadFloat();
            break;
          }
          case 48: {
            EmailVerified = input.ReadBool();
            break;
          }
          case 58: {
            phone_.AddEntriesFrom(input, _repeated_phone_codec);
            break;
          }
          case 65: {
            Salary = input.ReadDouble();
            break;
          }
          case 74: {
            myAdd_.AddEntriesFrom(input, _repeated_myAdd_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Address : pb::IMessage<Address> {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Simon.GrpcService.API.PersonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address(Address other) : this() {
      province_ = other.province_;
      city_ = other.city_;
      area_ = other.area_;
      zipCode_ = other.zipCode_;
      street_ = other.street_;
      number_ = other.number_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "province" field.</summary>
    public const int ProvinceFieldNumber = 1;
    private string province_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Province {
      get { return province_; }
      set {
        province_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 2;
    private string city_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "area" field.</summary>
    public const int AreaFieldNumber = 3;
    private string area_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Area {
      get { return area_; }
      set {
        area_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zip_code" field.</summary>
    public const int ZipCodeFieldNumber = 4;
    private string zipCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ZipCode {
      get { return zipCode_; }
      set {
        zipCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "street" field.</summary>
    public const int StreetFieldNumber = 5;
    private string street_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Street {
      get { return street_; }
      set {
        street_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 6;
    private string number_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Number {
      get { return number_; }
      set {
        number_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Province != other.Province) return false;
      if (City != other.City) return false;
      if (Area != other.Area) return false;
      if (ZipCode != other.ZipCode) return false;
      if (Street != other.Street) return false;
      if (Number != other.Number) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Province.Length != 0) hash ^= Province.GetHashCode();
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (Area.Length != 0) hash ^= Area.GetHashCode();
      if (ZipCode.Length != 0) hash ^= ZipCode.GetHashCode();
      if (Street.Length != 0) hash ^= Street.GetHashCode();
      if (Number.Length != 0) hash ^= Number.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Province.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Province);
      }
      if (City.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(City);
      }
      if (Area.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Area);
      }
      if (ZipCode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ZipCode);
      }
      if (Street.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Street);
      }
      if (Number.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Number);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Province.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Province);
      }
      if (City.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (Area.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Area);
      }
      if (ZipCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ZipCode);
      }
      if (Street.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Street);
      }
      if (Number.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Number);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      if (other.Province.Length != 0) {
        Province = other.Province;
      }
      if (other.City.Length != 0) {
        City = other.City;
      }
      if (other.Area.Length != 0) {
        Area = other.Area;
      }
      if (other.ZipCode.Length != 0) {
        ZipCode = other.ZipCode;
      }
      if (other.Street.Length != 0) {
        Street = other.Street;
      }
      if (other.Number.Length != 0) {
        Number = other.Number;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Province = input.ReadString();
            break;
          }
          case 18: {
            City = input.ReadString();
            break;
          }
          case 26: {
            Area = input.ReadString();
            break;
          }
          case 34: {
            ZipCode = input.ReadString();
            break;
          }
          case 42: {
            Street = input.ReadString();
            break;
          }
          case 50: {
            Number = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
